# Generated by Django 2.0.2 on 2020-01-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('standard', models.CharField(default='0', max_length=10)),
            ],
        ),
    ]
